FROM node:16-slim

WORKDIR /app

COPY package.json package.json
COPY yarn.lock yarn.lock
COPY .yarnrc.yml .yarnrc.yml
COPY .yarn .yarn 

COPY apps apps
COPY services services
COPY packages packages 

RUN yarn workspaces focus @hnu/workflow

CMD yarn workspace @hnu/workflow start
