---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: hnu
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: hnu/workflow:v1.0.0
        imagePullPolicy: IfNotPresent
        # resources:
        #   limits:
        #     memory: "512Mi"
        #     cpu: "200m"
        env:
        - name: TASK_QUEUE
          valueFrom:
            configMapKeyRef:
              name: hnu-config
              key: TaskQueue
        - name: TEMPORAL_SERVER
          valueFrom:
            configMapKeyRef:
              name: hnu-config
              key: TemporalServer
